# Generated by Django 5.2.14 on 2026-05-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_flashcard_ease_factor_flashcard_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='study.subject')),
            ],
            options={
                'unique_together': {('subject', 'day_of_week')},
            },
        ),
    ]
